# Generated by Django 3.1.7 on 2021-04-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='begin',
            new_name='created',
        ),
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='total_bids',
            field=models.IntegerField(default=0),
        ),
    ]
