# Generated by Django 3.1.7 on 2021-04-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210409_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
